using System;

namespace randomNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Enter a number between 1 and 2:");
            int userInput = int.Parse(Console.ReadLine());
            int randomNumber;

            Random randm = new Random();
            randomNumber = randm.Next(1, 2);

            if (userInput == randomNumber)
            {

                Console.WriteLine("Your number matches the random number picked by the program which was: " + randomNumber);
            }

            else
            {

                Console.WriteLine("Your number did not match the number generated by the program, which was: " + randomNumber);
            }
            
        }
    }
}
